version: '3.6'

volumes:
  gcars_data:
    driver: local
services:
  gcars_postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: gcars_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: gcars
    volumes:
      - gcars_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
  app:
    build: .
    ports:
      - 8087:8087
    depends_on:
      - gcars_postgresdb
    links:
      - gcars_postgresdb